# Generated by Django 3.2.2 on 2022-05-04 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dosage', models.IntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('intake_type', models.CharField(choices=[('Once Daily', 'DailyIntake'), ('Twice Daily', 'Twice DailyIntake'), ('Other', 'Any other')], default='Once Daily', max_length=20)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
