# Generated by Django 3.2.7 on 2022-01-16 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood', '0003_mood_feelings_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='feelingstag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reasonstag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
