# Generated by Django 3.2 on 2022-02-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_rename_dailygoals_dailygoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('discussion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('discussion', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailygoal',
            name='date_time',
        ),
    ]
