# Generated by Django 3.2 on 2022-02-25 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goal', '0003_auto_20220223_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('discussion', models.CharField(max_length=20)),
                ('goals_type', models.CharField(choices=[('Daily', 'Dailygoals'), ('Weekly', 'Weeklygoals'), ('Monthly', 'Monthlygoals')], default='Daily', max_length=9)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyGoal',
        ),
        migrations.DeleteModel(
            name='MonthlyGoal',
        ),
        migrations.DeleteModel(
            name='WeeklyGoal',
        ),
    ]
